sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_weather_providers;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_cities;'
  - mvn clean
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine